services:

  ratelimit_mysql_db:
    image: mysql:8.0
    container_name: ratelimit_mysql_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ratelimiter
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-padmin"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql_ratelimiter_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  kafka:
    image: bitnamilegacy/kafka:4.0.0-debian-12-r10
    container_name: kafka
    restart: unless-stopped
    ports:
      - "9092:9092"     # Internal Docker communication
      - "29092:29092"   # External host access
    environment:
        KAFKA_CFG_NODE_ID: 1
        KAFKA_CFG_PROCESS_ROLES: broker,controller
        KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
        KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
        KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
        KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
        KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
        ALLOW_PLAINTEXT_LISTENER: yes

#    volumes:
#      - kafka_data:/bitnami/kafka

#  kafka:
#    image: apache/kafka:4.1.1
#    container_name: kafka
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_NODE_ID: 1
#      KAFKA_PROCESS_ROLES: broker,controller
#      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
#      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
#      KAFKA_LOG_DIRS: /var/lib/kafka/data
#      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  rate-limiter:
    build: .
    container_name: rate-limiter-gateway
    restart: unless-stopped
    ports:
      - "9000:8080"

    depends_on:
      ratelimit_mysql_db:
        condition: service_healthy
      redis:
        condition: service_started
      kafka:
        condition: service_started

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://ratelimit_mysql_db:3306/ratelimiter
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin

      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379

      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

      BACKEND_BASE_URL: http://host.docker.internal:8080

    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  mysql_ratelimiter_data:
  redis_data: